name: Test Weather Data Bid

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Pull Docker image
      run: docker pull daisukekodaira/battery-control-by-reinforcement-learning:latest

    - name: Run tests
      run: docker run -v $PWD:/app -w /app daisukekodaira/battery-control-by-reinforcement-learning:latest pytest tests/test_datetime_dayAfterTomorrow.py
