name: Unit Test weather data bid

on:
  push:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest

    # Use the Dockerfile from the repository
    container:
      image: docker://docker.pkg.github.com/daisukekodaira/Battery-Control-by-Reinforcement-Learning/devcontainer:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r .devcontainer/requirements.txt

      - name: Run tests
        run: pytest tests/test_datetime_dayAfterTomorrow.py
