name: Test Weather Data Bid

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Pull Docker image
      run: docker pull daisukekodaira/battery-control-by-reinforcement-learning:latest

    - name: Run tests
      run: docker run -v $PWD:/app -w /app daisukekodaira/battery-control-by-reinforcement-learning:latest pytest tests/test_datetime_dayAfterTomorrow.py
